on: push
name: Build and Publish Front End Framework Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        
    - name: Build Project
      run: |
        npm cache clean --force
        npm install
        npm run build --if-present
        
    - name: List output files
      run: ls
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.netfirms.com
        FTP_USERNAME: ${{ secrets.ftp_username }}
        FTP_PASSWORD: ${{ secrets.ftp_password }}
        LOCAL_DIR: /DCHKIN/
        ARGS: --delete